import * as THREE from 'three';
import {initSDK,saveData,loadData,getMuteSetting} from './sdk.js';

const canvas=document.querySelector('#game'), hud=document.querySelector('#hud');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=!navigator.webdriver; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene(); scene.background=new THREE.Color('#89c8e4'); scene.fog=new THREE.Fog('#9ac7bc',42,135);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,180); const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight('#c9edff','#314a2d',2.1)); const sun=new THREE.DirectionalLight('#ffd891',3.1); sun.position.set(-45,60,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);
const world=new THREE.Group();scene.add(world); const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
const state={pos:V(0,0,16),vel:V(),hp:100,maxHp:100,stamina:100,level:1,xp:0,gold:12,inventory:['ironSword','oakShield','potion','potion','valeArmor'],equipped:'ironSword',tutorialStep:0,kills:0,playing:false,blocking:false,attack:0,attackTime:0,mouseMoved:false,fps:60,particles:[],mobs:[],loot:[],saved:false};
const items={ironSword:{icon:'⚔️',name:'Iron Sword',tip:'A trusty blade · +12 damage',damage:12},sunSword:{icon:'✨',name:'Sunsteel Sword',tip:'A radiant sword · +22 damage',damage:22},oakShield:{icon:'🛡️',name:'Oak Shield',tip:'Sturdy oak · blocks 65%'},potion:{icon:'🧪',name:'Red Potion',tip:'Restores 45 health'},valeArmor:{icon:'🥋',name:'Vale Guardmail',tip:'Light armor · +20 HP'},coin:{icon:'🟡',name:'Vale Coin',tip:'A gleaming coin'}};
function mat(c,rough=.8){return new THREE.MeshStandardMaterial({color:c,roughness:rough,flatShading:true})} const mats={grass:mat('#4f9a45'),dirt:mat('#a66d37'),rock:mat('#66706b'),wood:mat('#6c4025'),leaf:mat('#3e7b3d'),water:new THREE.MeshStandardMaterial({color:'#4aa8c7',roughness:.18,metalness:.15,transparent:true,opacity:.8}),gold:mat('#e8b84c',.35),skin:mat('#d99b73'),metal:mat('#b6c5cc',.35),cloth:mat('#355a91'),fire:mat('#ff9e32',.1)};
function mesh(geo,material,pos=V(),scale=1,parent=world){const m=new THREE.Mesh(geo,material);m.position.copy(pos);if(typeof scale==='number')m.scale.setScalar(scale);else m.scale.copy(scale);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
function height(x,z){return .85*Math.sin(x*.075)*Math.cos(z*.06)+.32*Math.sin((x+z)*.15)}
function terrain(){const g=new THREE.PlaneGeometry(200,200,80,80);const p=g.attributes.position;for(let i=0;i<p.count;i++){let x=p.getX(i),y=p.getY(i);p.setZ(i,height(x,y))}g.computeVertexNormals();const t=mesh(g,mats.grass);t.rotation.x=-Math.PI/2;t.receiveShadow=true;
 // dirt path and stream rendered just above terrain
 const path=mesh(new THREE.PlaneGeometry(7,112,1,32),mats.dirt,V(-2,.09,-20));path.rotation.x=-Math.PI/2;const a=path.geometry.attributes.position;for(let i=0;i<a.count;i++){let z=a.getY(i)-20;a.setZ(i,height(a.getX(i)-2,z)+.11)}path.geometry.computeVertexNormals();
 const water=mesh(new THREE.PlaneGeometry(26,17),mats.water,V(31,height(31,-4)+.13,-4));water.rotation.x=-Math.PI/2;water.name='water';
}
function tree(x,z,s=1){const y=height(x,z);mesh(new THREE.CylinderGeometry(.22*s,.38*s,3.1*s,6),mats.wood,V(x,y+1.5*s,z));for(let i=0;i<3;i++){const c=mesh(new THREE.ConeGeometry(1.7*s-i*.22*s,3*s,7),mats.leaf,V(x,y+3.1*s+i*.8*s,z));c.rotation.y=i*.6}}
function vegetation(){let seed=42;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647}, count=125, dummy=new THREE.Object3D();
 const trunk=new THREE.InstancedMesh(new THREE.CylinderGeometry(.22,.38,3.1,6),mats.wood,count), crowns=[0,1,2].map(i=>new THREE.InstancedMesh(new THREE.ConeGeometry(1.7-i*.22,3,7),mats.leaf,count));for(const x of [trunk,...crowns]){x.castShadow=x.receiveShadow=true;world.add(x)}let n=0;
 for(let i=0;i<count;i++){let x=rand()*184-92,z=rand()*184-92;if(Math.abs(x)<13&&z>-42&&z<30||x>18&&x<45&&z>-15&&z<10){i--;continue}let s=.65+rand()*.65,y=height(x,z);dummy.position.set(x,y+1.5*s,z);dummy.scale.setScalar(s);dummy.rotation.set(0,rand()*6,0);dummy.updateMatrix();trunk.setMatrixAt(n,dummy.matrix);for(let c=0;c<3;c++){dummy.position.set(x,y+3.1*s+c*.8*s,z);dummy.scale.setScalar(s);dummy.rotation.set(0,rand()*6,0);dummy.updateMatrix();crowns[c].setMatrixAt(n,dummy.matrix)}n++}trunk.count=n;crowns.forEach(c=>c.count=n);
 const blades=280,grass=new THREE.InstancedMesh(new THREE.ConeGeometry(.055,.7,3),mat('#6da94c'),blades),flowers=new THREE.InstancedMesh(new THREE.SphereGeometry(.09,5,4),mat('#f4a6bb'),24);world.add(grass,flowers);let f=0;for(let i=0;i<blades;i++){let x=rand()*130-65,z=rand()*110-55;if(Math.abs(x)<8){i--;continue}dummy.position.set(x,height(x,z)+.28,z);dummy.scale.setScalar(.5);dummy.rotation.set(.15,rand()*6,0);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);if(i%13===0&&f<24){dummy.position.set(x,height(x,z)+.65,z);dummy.scale.setScalar(1);dummy.updateMatrix();flowers.setMatrixAt(f++,dummy.matrix)}}flowers.count=f}
function cabin(x,z,r=0){const y=height(x,z);const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=r;world.add(g);mesh(new THREE.BoxGeometry(7,4,6),mat('#c38b53'),V(0,2,0),1,g);mesh(new THREE.ConeGeometry(5.5,3,4),mat('#754330'),V(0,5,0),1,g).rotation.y=Math.PI/4;mesh(new THREE.BoxGeometry(1.2,2,0.15),mat('#493223'),V(0,1,.1+3.05),1,g);for(let q of [-2,2])mesh(new THREE.BoxGeometry(1.1,1.1,.16),mat('#9bc7d4'),V(q,2.5,3.07),1,g)}
function village(){cabin(-12,5,.1);cabin(10,1,-.2);cabin(-11,-15,.3);cabin(13,-15,-.3);for(let i=-11;i<12;i+=2){let y=height(i,13);mesh(new THREE.CylinderGeometry(.07,.07,.8,5),mats.wood,V(i,y+.4,13));mesh(new THREE.CylinderGeometry(.07,.07,.8,5),mats.wood,V(i,y+.4,14.1))}
 const fire=new THREE.Group();fire.position.set(0,height(0,2),2);world.add(fire);for(let i=0;i<5;i++){let l=mesh(new THREE.CylinderGeometry(.13,.17,2.1,6),mats.wood,V(),1,fire);l.rotation.z=Math.PI/2;l.rotation.y=i*1.25}for(let i=0;i<9;i++){let f=mesh(new THREE.ConeGeometry(.25+Math.random()*.16,.9,5),mats.fire,V((Math.random()-.5)*.7,.45,(Math.random()-.5)*.7),1,fire);f.name='flame'}const light=new THREE.PointLight('#ffad45',12,18,2);light.position.copy(fire.position).add(V(0,2,0));scene.add(light);
 const dummy=makeHumanoid('#d6ad7a','#804b31');dummy.position.set(-4,height(-4,4),4);dummy.name='training dummy';world.add(dummy);state.dummy=dummy; const mentor=makeHumanoid('#e9bb8d','#7b4b93');mentor.position.set(3,height(3,3),3);mentor.name='Mentor Arlen';world.add(mentor);state.mentor=mentor}
function makeHumanoid(skin='#d99b73',cloth='#355a91'){const g=new THREE.Group(), body=new THREE.Group();g.add(body);const sm=mat(skin),cm=mat(cloth),boot=mat('#40332f');mesh(new THREE.CylinderGeometry(.42,.52,1.25,7),cm,V(0,1.75,0),1,body);mesh(new THREE.SphereGeometry(.43,8,6),sm,V(0,2.75,0),1,body);const armL=new THREE.Group(),armR=new THREE.Group(),legL=new THREE.Group(),legR=new THREE.Group();for(const [a,x] of [[armL,-.57],[armR,.57]]){a.position.set(x,2.3,0);body.add(a);mesh(new THREE.CylinderGeometry(.15,.18,.9,6),cm,V(0,-.42,0),1,a)}for(const [l,x] of [[legL,-.23],[legR,.23]]){l.position.set(x,1.18,0);body.add(l);mesh(new THREE.CylinderGeometry(.17,.19,1.05,6),boot,V(0,-.48,0),1,l)}const sword=new THREE.Group();sword.position.set(.7,1.95,0);body.add(sword);mesh(new THREE.BoxGeometry(.11,1.25,.08),mats.metal,V(0,-.53,0),1,sword);mesh(new THREE.BoxGeometry(.52,.09,.1),mats.gold,V(0,.02,0),1,sword);sword.rotation.z=-.25; const shield=mesh(new THREE.CylinderGeometry(.43,.43,.11,7),mat('#8a5a2b'),V(-.68,1.95,.04),1,body);shield.rotation.x=Math.PI/2;g.userData={body,armL,armR,legL,legR,sword,shield,phase:Math.random()*6};return g}
const player=makeHumanoid();player.position.copy(state.pos);world.add(player);
function makeEnemy(type,x,z){const root=new THREE.Group();let body;if(type==='Slime'){body=mesh(new THREE.SphereGeometry(.74,9,6),mat('#58be71'),V(0,.7,0),1,root);body.scale.y=.7;for(let q of [-.24,.24])mesh(new THREE.SphereGeometry(.07,5,4),mat('#fff'),V(q,.82,.53),1,root)}else{body=makeHumanoid('#aab2a8','#5c4a4c');body.scale.setScalar(.83);root.add(body);}
 root.position.set(x,height(x,z),z);world.add(root);const e={type,root,body,hp:type==='Slime'?36:52,max:type==='Slime'?36:52,home:V(x,0,z),cool:0,dead:false,ui:null};const ui=document.createElement('div');ui.className='nameplate';ui.innerHTML=`${type}<div class="enemybar"><i></i></div>`;hud.append(ui);e.ui=ui;state.mobs.push(e);return e}
function spawnMobs(){[["Slime",-8,-34],["Slime",4,-38],["Slime",12,-31],["Slime",-17,-47],["Slime",18,-49],["Slime",-3,-56],["Wolf",19,-38],["Wolf",-23,-36]].forEach(a=>makeEnemy(...a))}
function addRock(x,z,s=1){let r=mesh(new THREE.DodecahedronGeometry(s,0),mats.rock,V(x,height(x,z)+s*.5,z));r.scale.y=.7;r.rotation.set(Math.random(),Math.random(),0)}
terrain();vegetation();village();for(let i=0;i<40;i++){let x=(Math.random()-.5)*180,z=(Math.random()-.5)*180;if(Math.abs(x)>55||Math.abs(z)>55)addRock(x,z,1+Math.random()*3)}spawnMobs();
let yaw=0,pitch=-.22,locked=false,keys={}; canvas.addEventListener('click',()=>{if(!panelOpen())canvas.requestPointerLock();});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;state.playing=locked;if(locked){document.querySelector('#hint').style.display='none';sound('start')}});document.addEventListener('mousemove',e=>{if(!locked)return;yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0025,-.62,.34);if(Math.abs(e.movementX)+Math.abs(e.movementY)>2){state.mouseMoved=true;tutorial(1)}});
addEventListener('keydown',e=>{keys[e.code]=true;if(['Tab','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyI'||e.code==='Tab')toggleInv();if(e.code==='Digit1')drink();if(e.code==='KeyE')interact();if(e.code==='Escape')closePanels();if(['KeyW','KeyZ','KeyA','KeyS','KeyD'].includes(e.code))tutorial(0);if(e.code==='Space')tutorial(2)});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('mousedown',e=>{if(e.button===0)attack();if(e.button===2){state.blocking=true;tutorial(5)}});addEventListener('mouseup',e=>{if(e.button===2)state.blocking=false});
function panelOpen(){return document.querySelector('.open')!==null}function closePanels(){for(const x of document.querySelectorAll('.open'))x.classList.remove('open')}
function sound(kind){if(getMuteSetting()||!state.playing)return;try{const ac=window.__ac||(window.__ac=new AudioContext());let o=ac.createOscillator(),g=ac.createGain();o.type=kind==='hit'?'square':'sine';o.frequency.value=kind==='level'?660:kind==='hit'?130:kind==='attack'?210:330;g.gain.setValueAtTime(.035,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.12);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.14)}catch{}}
function attack(){if(!locked||state.attackTime>0||state.stamina<8)return;state.attack=(state.attack%3)+1;state.attackTime=.42;state.stamina-=8;sound('attack');tutorial(4);setTimeout(()=>{const forward=V(Math.sin(yaw),0,-Math.cos(yaw));for(const e of state.mobs){if(e.dead)continue;let d=e.root.position.clone().sub(player.position),len=d.length();if(len<3.2&&(len<.35||forward.dot(d.normalize())>.1))hurt(e,items[state.equipped].damage)}} ,120)}
function hurt(e,dmg){e.hp-=dmg;sound('hit');if(e.hp<=0)die(e)}function die(e){e.dead=true;e.root.visible=false;e.ui.remove();state.kills++;state.xp+=35;toast(`${e.type} defeated! +35 XP`);sound('level');for(let i=0;i<12;i++)state.particles.push({p:e.root.position.clone().add(V(0,.8,0)),v:V((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:1,color:e.type==='Slime'?'#7ee887':'#d1d7d0'});drop(e.root.position,Math.random()<.45?'potion':'coin');if(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.maxHp+=20;state.hp=state.maxHp;toast(`LEVEL ${state.level}! Stronger than before`)}setTimeout(()=>respawn(e),30000);tutorial(8)}function respawn(e){e.hp=e.max;e.dead=false;e.root.visible=true;e.root.position.copy(e.home);hud.append(e.ui)}
function drop(p,id){const g=new THREE.Group();const orb=mesh(new THREE.IcosahedronGeometry(.22,1),id==='coin'?mats.gold:mat('#df575a'),V(0,.45,0),1,g);g.position.copy(p);world.add(g);state.loot.push({id,root:g});}
function interact(){let near=state.loot.find(l=>l.root.position.distanceTo(player.position)<2.4);if(near){state.inventory.push(near.id);near.root.removeFromParent();state.loot.splice(state.loot.indexOf(near),1);toast(`Picked up ${items[near.id].name}`);tutorial(6);return}if(state.mentor.position.distanceTo(player.position)<3){document.querySelector('#dialogue').classList.add('open');document.exitPointerLock();tutorial(7)}else toast('Move closer to interact')}
function drink(){let i=state.inventory.indexOf('potion');if(i<0)return toast('No potions');state.inventory.splice(i,1);state.hp=Math.min(state.maxHp,state.hp+45);sound('level');toast('Potion restored health')}
function toggleInv(){document.querySelector('#inventory').classList.toggle('open');if(panelOpen())document.exitPointerLock();renderInventory();tutorial(6)}document.querySelector('#invClose').onclick=closePanels;document.querySelector('#dialogClose').onclick=closePanels;document.querySelector('#endClose').onclick=closePanels;document.querySelector('#dialogNext').onclick=()=>{closePanels();tutorial(8);toast('Defeat three slimes on the meadow!')};
function renderInventory(){const grid=document.querySelector('#grid');grid.innerHTML='';for(let n=0;n<20;n++){let id=state.inventory[n],el=document.createElement('div');el.className='item';if(id){let it=items[id];el.innerHTML=`${it.icon}<span>${it.name}</span>`;el.dataset.tip=it.tip;el.onclick=()=>{if(id.includes('Sword')){state.equipped=id;document.querySelector('#eqWeapon').textContent=it.name;toast(`${it.name} equipped`);tutorial(6)}}}grid.append(el)}}
const steps=['Move with <b>WASD</b>','Look around with the <b>mouse</b>','Jump over the fence: <b>SPACE</b>','Hold <b>SHIFT</b> to sprint','Strike the training dummy: <b>LMB</b>','Hold <b>RMB</b> to block','Press <b>E</b> to pick up a sword','Press <b>I</b> to open inventory and equip it','Speak to Mentor Arlen, then defeat <b>3 Slimes</b>'];
function tutorial(n){if(n===8&&state.kills<3)return;if(n<state.tutorialStep)return;if(n===8&&state.kills>=3){state.tutorialStep=9;document.querySelector('#end').classList.add('open');save();return}if(n===state.tutorialStep||n>state.tutorialStep){state.tutorialStep=Math.min(n+1,8);save()}}
document.querySelector('#quest').onclick=()=>{state.tutorialStep=9;document.querySelector('#end').classList.add('open')};
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.style.opacity=1;setTimeout(()=>e.style.opacity=0,1800)}
function save(){saveData('aetherblade.save',JSON.stringify({level:state.level,xp:state.xp,inventory:state.inventory,equipped:state.equipped,tutorialStep:state.tutorialStep}));}function load(){try{let s=JSON.parse(loadData('aetherblade.save'));if(s){for(let k of ['level','xp','inventory','equipped','tutorialStep'])if(s[k]!=null)state[k]=s[k]}}catch{}}
load();renderInventory();
function updatePlayer(dt){let f=V(Math.sin(yaw),0,-Math.cos(yaw)),r=V(f.z,0,-f.x),move=V();if(keys.KeyW||keys.KeyZ)move.add(f);if(keys.KeyS)move.sub(f);if(keys.KeyD)move.add(r);if(keys.KeyA)move.sub(r);let sprint=keys.ShiftLeft||keys.ShiftRight;if(move.lengthSq()){move.normalize();let speed=sprint&&state.stamina>2?8.5:5.1;state.pos.addScaledVector(move,speed*dt);state.stamina=Math.max(0,state.stamina-(sprint?21:0)*dt);player.rotation.y=Math.atan2(move.x,move.z);tutorial(3)}else state.stamina=Math.min(100,state.stamina+16*dt);if(keys.Space&&state.pos.y<=height(state.pos.x,state.pos.z)+.02){state.vel.y=8.2;keys.Space=false}state.vel.y-=22*dt;state.pos.y+=state.vel.y*dt;let ground=height(state.pos.x,state.pos.z);if(state.pos.y<ground){state.pos.y=ground;state.vel.y=0}let radial=Math.hypot(state.pos.x,state.pos.z);if(radial>91){state.pos.multiplyScalar(91/radial);toast('The ancient forest bars your path')}player.position.copy(state.pos);let u=player.userData,walk=move.lengthSq()?Math.sin(performance.now()*.012*(sprint?1.5:1)):0;u.legL.rotation.x=walk*.7;u.legR.rotation.x=-walk*.7;u.armL.rotation.x=-walk*.55;u.armR.rotation.x=walk*.55;if(state.attackTime>0){state.attackTime-=dt;u.sword.rotation.z=-.25+Math.sin((.42-state.attackTime)*12)*1.7}else u.sword.rotation.z=-.25;u.shield.visible=state.blocking}
function updateMobs(dt){for(const e of state.mobs){if(e.dead)continue;let d=player.position.clone().sub(e.root.position);d.y=0;let len=d.length(),speed=e.type==='Wolf'?2.2:1.35;if(len<19&&len>2.1){d.normalize();if(e.type==='Wolf')d.applyAxisAngle(V(0,1,0),.8*Math.sin(performance.now()*.001));e.root.position.addScaledVector(d,speed*dt);e.root.position.y=height(e.root.position.x,e.root.position.z)}if(len<2.4&&e.cool<=0){e.cool=1.3;setTimeout(()=>{if(!e.dead&&e.root.position.distanceTo(player.position)<3){state.hp=Math.max(0,state.hp-(state.blocking?3:10));sound('hit');if(!state.hp)forceGameOver()}},480)}e.cool-=dt;let ndc=e.root.position.clone().add(V(0,1.8,0)).project(camera);e.ui.style.left=((ndc.x+1)*innerWidth/2)+'px';e.ui.style.top=((-ndc.y+1)*innerHeight/2)+'px';e.ui.style.display=ndc.z<1?'block':'none';e.ui.querySelector('i').style.width=Math.max(0,e.hp/e.max*100)+'%'}}
function updateParticles(dt){for(let i=state.particles.length-1;i>=0;i--){let q=state.particles[i];q.life-=dt;q.p.addScaledVector(q.v,dt);q.v.y-=8*dt;if(!q.m){q.m=mesh(new THREE.SphereGeometry(.08,4,3),mat(q.color),q.p)}q.m.position.copy(q.p);q.m.scale.setScalar(q.life);if(q.life<=0){q.m.removeFromParent();state.particles.splice(i,1)}}}
function forceGameOver(){toast('You were knocked out — restored at campfire');state.hp=state.maxHp;state.pos.set(0,height(0,16),16)}
function updateCamera(dt){let desired=state.pos.clone().add(V(Math.sin(yaw)*7,3.8,-Math.cos(yaw)*7));desired.y=Math.max(desired.y,height(desired.x,desired.z)+1.1);camera.position.lerp(desired,1-Math.exp(-dt*8));camera.lookAt(state.pos.clone().add(V(0,1.65,0)));}
function renderUI(){document.querySelector('#hp').style.width=state.hp/state.maxHp*100+'%';document.querySelector('#st').style.width=state.stamina+'%';document.querySelector('#xp').style.width=state.xp/(state.level*100)*100+'%';document.querySelector('#level').textContent=`Level ${state.level} · ${state.xp} / ${state.level*100} XP`;let s=state.tutorialStep;document.querySelector('#quest').innerHTML=s<9?`Tutorial ${s+1}/9 · ${steps[s]} <button id="skip">Skip tutorial</button>`:'Free exploration · Emerald Vale';let skip=document.querySelector('#skip');if(skip)skip.onclick=()=>{state.tutorialStep=9;document.querySelector('#end').classList.add('open');save()};}
let frames=0,lastF=performance.now();function frame(){let dt=Math.min(clock.getDelta(),.05),t=performance.now();frames++;if(t-lastF>500){state.fps=Math.round(frames*1000/(t-lastF));frames=0;lastF=t}for(const o of scene.getObjectByName('water')?[scene.getObjectByName('water')]:[])o.material.color.offsetHSL(0,0,Math.sin(t*.002)*.001);for(const f of world.children)f.traverse?.(o=>{if(o.name==='flame')o.scale.y=.8+Math.sin(t*.01+o.id)*.25});updatePlayer(dt);updateMobs(dt);updateParticles(dt);updateCamera(dt);renderUI();renderer.render(scene,camera);requestAnimationFrame(frame)}
addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
initSDK();
window.__astro={getState:()=>({state:'playing',pos:{x:state.pos.x,y:state.pos.y,z:state.pos.z},hp:state.hp,stamina:state.stamina,level:state.level,xp:state.xp,mobs:state.mobs.map(m=>({type:m.type,hp:m.hp,dist:m.root.position.distanceTo(state.pos)})),inventory:state.inventory,equipped:state.equipped,tutorialStep:state.tutorialStep,fps:state.fps,particles:state.particles.length}),teleport:(x,z)=>{state.pos.set(x,height(x,z),z)},giveItem:id=>{state.inventory.push(id);renderInventory()},killMob:i=>{let m=state.mobs[i];if(m&&!m.dead)die(m)},setHp:n=>state.hp=n,completeTutorialStep:()=>tutorial(state.tutorialStep),forceGameOver,soak:(seconds=120)=>{for(let i=0;i<seconds*60;i++){updatePlayer(1/60);updateMobs(1/60);updateParticles(1/60)}}};
frame();
